CREATE TABLE IF NOT EXISTS CARS(
CARS_ID INTEGER PRIMARY KEY,
NAME TEXT,
HORSEPOWER INTEGER
);

INSERT INTO CARS(CARS_ID, NAME, HORSEPOWER)
VALUES
(1, 'Mazda Miata', 181),
(2, 'Fiat Multipla', 110),
(3, 'Chrysler PT Cruiser', 140);

SELECT COUNT(CARS_ID) AS CARS_Count
FROM CARS;

SELECT SUM(HORSEPOWER) AS Total_Horsepower
FROM CARS;

SELECT * FROM CARS;
